#!/usr/bin/env python3
"""
update_build_log.py — Append a new session entry to AutoShopPro_Build_Log.docx
Usage: python3 docs/update_build_log.py

Reads session data from the SESSION dict below, then inserts the entry
directly after the "Build Sessions" heading in the document.

Requires: pip3 install python-docx
"""

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os

DOCX_PATH = os.path.join(os.path.dirname(__file__), 'AutoShopPro_Build_Log.docx')

# ── Fill this in at the end of each session ───────────────────────────────────
SESSION = {
    'heading':  'Session 5 — v0.4.0 Open Bay',
    'date':     'March 22, 2026',
    'version':  'v0.4.0 Open Bay',
    'number':   '5',
    'built': [
        'Repair Orders table — schema v9, full CRUD (insertRepairOrder, updateRepairOrder, deleteRepairOrder, watchAllRepairOrders, watchRepairOrder, watchRoForEstimate)',
        'RepairOrderWithDetails helper class for joined RO + customer + vehicle queries',
        'repair_orders_provider.dart — repairOrdersProvider, repairOrderProvider, roForEstimateProvider (Riverpod StreamProviders)',
        'RO list screen — color-coded status dots (blue=Open, orange=In Progress, green=Completed, gray=Closed), customer name, vehicle label, status text + chevron',
        'RO detail screen — status badge, customer/vehicle header, line items (read from linked estimate), totals, ACTIONS section with status advancement row',
        'Status advancement flow: Open → In Progress → Completed → Closed, each with contextual icon (wrench / checkmark / lock)',
        'Convert to Repair Order action on estimate detail screen (list-row style under ACTIONS)',
        'View Repair Order link on estimate detail once RO exists (green icon, RO number subtitle)',
        'Repair Orders hub row enabled — was Coming soon, now navigates to /repair-orders/ros',
        'Button/action design rule standardized — all actions use list-row style (blue icon + blue label + gray chevron, under small-caps section header)',
        'Design rule saved permanently to CLAUDE.md so all future sessions follow it',
        'Version renamed from v0.3.0 Estimate → v0.3.0 Write-Up across all docs',
    ],
    'bugs': [],
    'files_added': [
        'lib/features/repair_orders/repair_orders_provider.dart',
        'lib/features/repair_orders/ro_list_screen.dart',
        'lib/features/repair_orders/ro_detail_screen.dart',
    ],
    'files_modified': [
        'lib/database/database.dart — RepairOrders table, RepairOrderWithDetails, schemaVersion 8→9, migration from < 9, RO queries',
        'lib/database/database.g.dart — regenerated by build_runner',
        'lib/features/estimates/estimate_detail_screen.dart — Convert to RO / View RO banner, Add Labor/Part as list-row actions, _ActionRow widget, removed _AddButton',
        'lib/features/repair_orders/repair_orders_screen.dart — Repair Orders row enabled, navigates to /repair-orders/ros',
        'lib/router.dart — /repair-orders/ros and /repair-orders/ros/:roId routes added',
        'CLAUDE.md — Button & Action Design Rule section added, What\'s Built So Far updated, schema v9, version bumped to v0.4.0 Open Bay',
        'docs/module_plan.md — RO tasks checked off, v0.4.0 infrastructure section added',
        'README.md — v0.4.0 Open Bay added to Project Status',
    ],
    'next': 'Polish and bug-finding session — review all screens for UX issues, fix any rough edges, check edge cases (empty states, missing data, navigation flows).',
}
# ──────────────────────────────────────────────────────────────────────────────


def add_bold_label(para, label):
    run = para.add_run(label)
    run.bold = True


def add_kv_row(doc, label, value):
    """Add a label: value line (bold label, normal value)."""
    para = doc.add_paragraph(style='Normal')
    add_bold_label(para, f'{label}: ')
    para.add_run(value)


def add_section(doc, label, items):
    """Add a bold label followed by bulleted items."""
    if not items:
        return
    para = doc.add_paragraph(style='Normal')
    add_bold_label(para, label)
    for item in items:
        doc.add_paragraph(item, style='List Bullet')


def insert_session(session):
    doc = Document(DOCX_PATH)

    # Find the paragraph index of "Build Sessions" heading
    insert_idx = None
    for i, para in enumerate(doc.paragraphs):
        if 'Build Sessions' in para.text:
            insert_idx = i
            break

    if insert_idx is None:
        print("ERROR: Could not find 'Build Sessions' heading in document.")
        return

    # python-docx can't insert paragraphs at an arbitrary position directly,
    # so we use the underlying XML to splice in after the target paragraph.
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
    import copy

    body = doc.element.body
    all_paras = body.findall(f'.//{qn("w:p")}')
    target_para_el = doc.paragraphs[insert_idx]._element

    def make_para(text, bold=False, style_id=None):
        p = OxmlElement('w:p')
        if style_id:
            pPr = OxmlElement('w:pPr')
            pStyle = OxmlElement('w:pStyle')
            pStyle.set(qn('w:val'), style_id)
            pPr.append(pStyle)
            p.append(pPr)
        r = OxmlElement('w:r')
        if bold:
            rPr = OxmlElement('w:rPr')
            b = OxmlElement('w:b')
            rPr.append(b)
            r.append(rPr)
        t = OxmlElement('w:t')
        t.text = text
        t.set('{http://www.w3.org/XML/1998/namespace}space', 'preserve')
        r.append(t)
        p.append(r)
        return p

    def make_bullet(text):
        p = OxmlElement('w:p')
        pPr = OxmlElement('w:pPr')
        pStyle = OxmlElement('w:pStyle')
        pStyle.set(qn('w:val'), 'ListBullet')
        pPr.append(pStyle)
        p.append(pPr)
        r = OxmlElement('w:r')
        t = OxmlElement('w:t')
        t.text = text
        t.set('{http://www.w3.org/XML/1998/namespace}space', 'preserve')
        r.append(t)
        p.append(r)
        return p

    # Build the block of new XML elements (in reverse order, each inserted after target)
    blocks = []

    # Next session
    blocks.append(make_para('Next session'))
    blocks.append(make_para(session['next']))

    # Files modified
    if session['files_modified']:
        blocks.append(make_para('Files modified', bold=True))
        for f in session['files_modified']:
            blocks.append(make_bullet(f))

    # Files added
    if session['files_added']:
        blocks.append(make_para('Files added', bold=True))
        for f in session['files_added']:
            blocks.append(make_bullet(f))

    # Bugs
    if session['bugs']:
        blocks.append(make_para('Bugs fixed', bold=True))
        for b in session['bugs']:
            blocks.append(make_bullet(b))

    # What was built
    if session['built']:
        blocks.append(make_para('What was built', bold=True))
        for item in session['built']:
            blocks.append(make_bullet(item))

    # Metadata rows
    blocks.append(make_para(f"Session: {session['number']}"))
    blocks.append(make_para(f"Version: {session['version']}"))
    blocks.append(make_para(f"Date: {session['date']}"))

    # Section heading
    blocks.append(make_para(session['heading'], style_id='Heading2'))

    # Blank line before heading
    blocks.append(make_para(''))

    # Insert all blocks after the "Build Sessions" heading (reversed so order is correct)
    ref = target_para_el
    for block in blocks:
        ref.addnext(block)

    doc.save(DOCX_PATH)
    print(f"✅ Session entry '{session['heading']}' added to {DOCX_PATH}")


def read_build_log():
    """Print the build log contents to the terminal."""
    doc = Document(DOCX_PATH)
    for para in doc.paragraphs:
        text = para.text.strip()
        if not text:
            continue
        style = para.style.name if para.style else ''
        if 'Heading 1' in style:
            print(f'\n=== {text} ===')
        elif 'Heading 2' in style:
            print(f'\n--- {text} ---')
        elif 'List' in style:
            print(f'  • {text}')
        else:
            print(text)


if __name__ == '__main__':
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == 'read':
        read_build_log()
    else:
        insert_session(SESSION)
